"""fix cascade: set null for teacher/grade/assignment/audit refs, restore submission_telemetry

Revision ID: 13e47a346ddc
Revises: 64ee942c63b8
Create Date: 2026-04-25 22:29:59.145051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e47a346ddc'
down_revision: Union[str, None] = '64ee942c63b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('typed_chars', sa.Integer(), nullable=True),
    sa.Column('paste_count', sa.Integer(), nullable=True),
    sa.Column('pasted_chars', sa.Integer(), nullable=True),
    sa.Column('keystroke_count', sa.Integer(), nullable=True),
    sa.Column('active_typing_seconds', sa.Float(), nullable=True),
    sa.Column('avg_wpm', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['assignment_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_submission_telemetry_id'), 'submission_telemetry', ['id'], unique=False)
    op.alter_column('assignments', 'publisher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('assignments_publisher_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'users', ['publisher_id'], ['id'], ondelete='SET NULL')
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('audit_logs_actor_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('class_subjects_teacher_id_fkey', 'class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_subjects', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.alter_column('grades', 'graded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('grades_graded_by_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'users', ['graded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_graded_by_fkey', 'grades', 'users', ['graded_by'], ['id'], ondelete='CASCADE')
    op.alter_column('grades', 'graded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key('class_subjects_teacher_id_fkey', 'class_subjects', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_actor_id_fkey', 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_publisher_id_fkey', 'assignments', 'users', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('assignments', 'publisher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_submission_telemetry_id'), table_name='submission_telemetry')
    op.drop_table('submission_telemetry')
    # ### end Alembic commands ###
