"""empty message

Revision ID: 4a17117afb99
Revises: 65542a456364
Create Date: 2026-03-26 07:12:26.919348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a17117afb99'
down_revision: Union[str, None] = '65542a456364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
