"""add is_quiz to assignments

Revision ID: 548bd53f7eaa
Revises: 13e47a346ddc
Create Date: 2026-04-27 02:54:15.455404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548bd53f7eaa'
down_revision: Union[str, None] = '13e47a346ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_quiz', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'is_quiz')
    # ### end Alembic commands ###
