"""add cascade delete to user foreign keys

Revision ID: 64ee942c63b8
Revises: 0006_submission_telemetry
Create Date: 2026-04-25 21:39:11.177319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64ee942c63b8'
down_revision: Union[str, None] = '0006_submission_telemetry'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_telemetry_id', table_name='submission_telemetry')
    op.drop_table('submission_telemetry')
    op.drop_constraint('announcements_author_id_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('assignment_submissions_student_id_fkey', 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_submissions', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('assignments_publisher_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'users', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attendance', 'marked_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('attendance_student_id_fkey', 'attendance', type_='foreignkey')
    op.drop_constraint('attendance_marked_by_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'users', ['marked_by_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('audit_logs_actor_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('behavior_logs_student_id_fkey', 'behavior_logs', type_='foreignkey')
    op.create_foreign_key(None, 'behavior_logs', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('class_subjects_teacher_id_fkey', 'class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_subjects', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('classes_home_teacher_id_fkey', 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'users', ['home_teacher_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('enrollments_student_id_fkey', 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('grades_graded_by_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'users', ['graded_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint('materials_uploader_id_fkey', 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'users', ['uploader_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key('materials_uploader_id_fkey', 'materials', 'users', ['uploader_id'], ['id'])
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_graded_by_fkey', 'grades', 'users', ['graded_by'], ['id'])
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key('enrollments_student_id_fkey', 'enrollments', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key('classes_home_teacher_id_fkey', 'classes', 'users', ['home_teacher_id'], ['id'])
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key('class_subjects_teacher_id_fkey', 'class_subjects', 'users', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'behavior_logs', type_='foreignkey')
    op.create_foreign_key('behavior_logs_student_id_fkey', 'behavior_logs', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_actor_id_fkey', 'audit_logs', 'users', ['actor_id'], ['id'])
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_marked_by_id_fkey', 'attendance', 'users', ['marked_by_id'], ['id'])
    op.create_foreign_key('attendance_student_id_fkey', 'attendance', 'users', ['student_id'], ['id'])
    op.alter_column('attendance', 'marked_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_publisher_id_fkey', 'assignments', 'users', ['publisher_id'], ['id'])
    op.drop_constraint(None, 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key('assignment_submissions_student_id_fkey', 'assignment_submissions', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key('announcements_author_id_fkey', 'announcements', 'users', ['author_id'], ['id'])
    op.create_table('submission_telemetry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typed_chars', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paste_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pasted_chars', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keystroke_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_typing_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_wpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='submission_telemetry_student_id_fkey'),
    sa.ForeignKeyConstraint(['submission_id'], ['assignment_submissions.id'], name='submission_telemetry_submission_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='submission_telemetry_pkey'),
    sa.UniqueConstraint('submission_id', name='submission_telemetry_submission_id_key')
    )
    op.create_index('ix_submission_telemetry_id', 'submission_telemetry', ['id'], unique=False)
    # ### end Alembic commands ###
