"""add schedules notifications

Revision ID: 65542a456364
Revises: 0004
Create Date: 2026-03-26 05:48:43.905053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65542a456364'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('announcement', 'assignment', 'alert', 'grade', 'general', name='notificationtype'), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('class_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_subject_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_subject_id', 'day_of_week', 'start_time', name='uq_schedule_slot')
    )
    op.create_index(op.f('ix_class_schedules_class_subject_id'), 'class_schedules', ['class_subject_id'], unique=False)
    op.create_index(op.f('ix_class_schedules_id'), 'class_schedules', ['id'], unique=False)
    op.alter_column('assignment_submissions', 'is_late',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('assignments', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('assignments', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='assignmentstatus'),
               nullable=True,
               existing_server_default=sa.text("'draft'::assignmentstatus"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('assignments', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'closed', name='assignmentstatus'),
               nullable=False,
               existing_server_default=sa.text("'draft'::assignmentstatus"))
    op.alter_column('assignments', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('assignment_submissions', 'is_late',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_class_schedules_id'), table_name='class_schedules')
    op.drop_index(op.f('ix_class_schedules_class_subject_id'), table_name='class_schedules')
    op.drop_table('class_schedules')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
