"""add payload column to audit_logs

Revision ID: b55806d3b1d0
Revises: cb11a30e8bb4
Create Date: 2026-04-20 01:24:35.315280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55806d3b1d0'
down_revision: Union[str, None] = 'cb11a30e8bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'payload')
    # ### end Alembic commands ###
