"""add max_attempts to assignments

Revision ID: fdb6de1dc3a2
Revises: b55806d3b1d0
Create Date: 2026-04-20 20:14:30.067327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb6de1dc3a2'
down_revision: Union[str, None] = 'b55806d3b1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('max_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'max_attempts')
    # ### end Alembic commands ###
