import {
    LayoutDashboard,
    Users,
    BookOpen,
    Calendar,
    Settings,
    GraduationCap,
    ClipboardList,
    FileText,
    BarChart3,
    UserCircle,
    ShieldAlert,
    School,
    Warehouse,
    Megaphone,
    MessageSquare,
    CalendarCheck,
    Book,
    Scale,
    CircleCheckBig,
    SquarePen,
    Calendar1
} from "lucide-react";

export const navigation = {
    admin: [
        { name: "Dashboard", href: "/admin", icon: LayoutDashboard },
        { name: "Users", href: "/admin/users", icon: Users },
        { name: "Teachers", href: "/admin/teachers", icon: Users },
        { name: "Students", href: "/admin/students", icon: GraduationCap },
        { name: "Classes", href: "/admin/classes", icon: Warehouse },
        { name: "Subjects", href: "/admin/subjects", icon: BookOpen },
        { name: "Oversight", href: "/admin/oversight", icon: BarChart3 },
        { name: "Analytics", href: "/admin/analytics", icon: BarChart3 },
        { name: "School", href: "/admin/school", icon: School },
        { name: "Schedule", href: "/admin/schedule", icon: Calendar },
        { name: "Settings", href: "/admin/settings", icon: Settings },
    ],
    teacher: [
        { name: "Dashboard", href: "/teacher", icon: LayoutDashboard },
        { name: "My Classes", href: "/teacher/classes", icon: BookOpen },
        { name: "People", href: "/teacher/people", icon: Users },
        { name: "Analytics", href: "/teacher/analytics", icon: BarChart3 },
        { name: "Assignments", href: "/teacher/assignments", icon: ClipboardList },
        { name: "Announcements", href: "/teacher/announcements", icon: Megaphone },
        { name: "Quizzes", href: "/teacher/quizzes", icon: FileText },
        { name: "Grading", href: "/teacher/grading", icon: ClipboardList },
        { name: "Behavior", href: "/teacher/behavior", icon: ShieldAlert },
        { name: "Schedule", href: "/teacher/schedule", icon: Calendar },
        { name: "Lessons", href: "/teacher/lessons", icon: BookOpen },
        { name: "School Policy", href: "/teacher/school-policy", icon: Scale },
        { name: "Discussion", href: "/teacher/discussion", icon: MessageSquare },
        { name: "Profile", href: "/teacher/profile", icon: UserCircle },
    ],
    "home-class-teacher": [
        { name: "Dashboard", href: "/home-class-teacher", icon: LayoutDashboard },
        { name: "People", href: "/home-class-teacher/people", icon: Users },
        { name: "Rankings", href: "/home-class-teacher/rankings", icon: ClipboardList },
        { name: "Behavior", href: "/home-class-teacher/behavior", icon: ShieldAlert },
        { name: "Analytics", href: "/home-class-teacher/analytics", icon: BarChart3 },
        { name: "Schedule", href: "/home-class-teacher/schedule", icon: Calendar },
        { name: "Announcements", href: "/home-class-teacher/announcements", icon: Megaphone },
        { name: "Discussions", href: "/home-class-teacher/discussions", icon: MessageSquare },
        { name: "School Policy", href: "/home-class-teacher/school-policy", icon: Scale },
        { name: "Profile", href: "/home-class-teacher/profile", icon: UserCircle },
    ],
    student: [
        { name: "Dashboard", href: "/student", icon: LayoutDashboard },
        { name: "My Schedule", href: "/student/schedule", icon: Calendar1 },
        { name: "To Do", href: "/student/todo", icon: CircleCheckBig },
        { name: "Attendance", href: "/student/attendance", icon: CalendarCheck },
        { name: "Lessons", href: "/student/lessons", icon: BookOpen },
        { name: "Assignments", href: "/student/assignments", icon: ClipboardList },
        { name: "Quizzes", href: "/student/quizzes", icon: FileText },
        { name: "Syllabus", href: "/student/syllabus", icon: Book },
        { name: "Grades", href: "/student/grades", icon: SquarePen },
        { name: "Analytics", href: "/student/analytics", icon: BarChart3 },
        { name: "People", href: "/student/people", icon: Users },
        { name: "Discussions", href: "/student/discussions", icon: MessageSquare },
        { name: "Announcements", href: "/student/announcements", icon: Megaphone },
        { name: "School Policy", href: "/student/school-policy", icon: Scale },
        { name: "Profile", href: "/student/profile", icon: UserCircle },
    ],
    // Add other roles as needed
};
